apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: go-service-obs
  labels:
    app: jaeger
    version: v1
spec:
  selector:
    app: jaeger
    version: v1
  ports:
  - name: grpc-jaeger
    port: 14250
    targetPort: 14250
  - name: http-jaeger
    port: 14268
    targetPort: 14268
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
  - name: http-otlp
    port: 4318
    targetPort: 4318
  - name: http-zipkin
    port: 9411
    targetPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: go-service-obs
  labels:
    app: jaeger
    version: v1
spec:
  selector:
    app: jaeger
    version: v1
  ports:
  - port: 16686
    targetPort: 16686
    name: http