apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      version: v1
  template:
    metadata:
      labels:
        app: loki
        version: v1
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
        - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9096
          name: grpc
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
        - name: loki-storage
          mountPath: /tmp/loki
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
      - name: loki-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http-loki
  - port: 9096
    targetPort: 9096
    protocol: TCP
    name: grpc-loki
  selector:
    app: loki