apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
  labels:
    app: go-microservice
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-microservice
      version: v1
  template:
    metadata:
      labels:
        app: go-microservice
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
      - name: go-microservice
        image: docker.io/aira18/go-microservice:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OTEL_SERVICE_NAME
          value: "go-microservice"
        - name: OTEL_SERVICE_VERSION
          value: "v1"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.medi.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=go-microservice,service.version=v1,service.namespace=medi"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /v1/ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5