apiVersion: v1
kind: Service
metadata:
  name: go-microservice
  namespace: go-service-obs
  labels:
    app: go-microservice
spec:
  selector:
    app: go-microservice
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP