apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: go-service-obs
  labels:
    app: grafana
    version: v1
    service: grafana
spec:
  selector:
    app: grafana
    version: v1
  ports:
  - port: 3000
    targetPort: 3000
    name: web