apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: go-microservice-vs
spec:
  hosts:
  - "*"
  gateways:
  - go-microservice-gateway
  http:
  - match:
    - uri:
        prefix: /v1/
    route:
    - destination:
        host: go-microservice
        port:
          number: 8080
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: 5xx,reset,connect-failure,refused-stream