apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: go-service-obs
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
    name: http
  - port: 9096
    targetPort: 9096
    name: grpc