apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: go-service-obs
  labels:
    app: prometheus
    version: v1
spec:
  selector:
    app: prometheus
    version: v1
  ports:
  - port: 9090
    targetPort: 9090
    name: http