apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
      version: v1
  template:
    metadata:
      labels:
        app: otel-collector
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.91.0
        command:
        - "/otelcol-contrib"
        - "--config=/etc/otel-collector-config/config.yaml"
        ports:
        - containerPort: 4317   # OTLP gRPC receiver
          name: otlp-grpc
        - containerPort: 4318   # OTLP HTTP receiver
          name: otlp-http
        - containerPort: 8889   # Prometheus metrics
          name: prometheus
        - containerPort: 8888   # Collector metrics
          name: metrics
        - containerPort: 13133  # Health check
          name: health
        - containerPort: 55679  # zPages
          name: zpages
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /etc/otel-collector-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 4317
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: otel-collector-config-vol
        configMap:
          name: otel-collector-config
          items:
          - key: config.yaml
            path: config.yaml