apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: http-otlp
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: http-prometheus
    port: 8889
    targetPort: 8889
    protocol: TCP
  - name: http-metrics
    port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: otel-collector