apiVersion: v1
kind: Service
metadata:
  name: product-service
  ## namespace: medisupply
  labels:
    app: product-service
    service: product-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
  selector:
    app: product-service
  type: ClusterIP
