apiVersion: v1
kind: Service
metadata:
  name: purchase-order-service
  namespace: medisupply
  labels:
    app: purchase-order-service
    service: purchase-order-service
spec:
  ports:
  - port: 8200
    targetPort: 8200
    name: http
    protocol: TCP
  selector:
    app: purchase-order-service
  type: ClusterIP
