apiVersion: v1
kind: Service
metadata:
  name: purchase-plan-service
  ## namespace: medisupply
  labels:
    app: purchase-plan-service
    service: purchase-plan-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
    protocol: TCP
  selector:
    app: purchase-plan-service
  type: ClusterIP
