apiVersion: v1
kind: ConfigMap
metadata:
  name: purchase-plan-service-config
  ## namespace: medisupply
  labels:
    app: purchase-plan-service
    version: v1
data:
  APP_ENV: "prod"
  HTTP_PORT: ":8081"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
