apiVersion: v1
kind: ConfigMap
metadata:
  name: purchase-order-service-config
  ## namespace: medisupply
  labels:
    app: purchase-order-service
    version: v1
data:
  APP_ENV: "prod"
  HTTP_PORT: ":8200"
  WAREHOUSE_SERVICE_URL: "http://warehouse-service:8100"
