apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  ## namespace: medisupply
  labels:
    app: supplier-service
    service: supplier-service
spec:
  ports:
  - port: 8082
    targetPort: 8082
    name: http
    protocol: TCP
  selector:
    app: supplier-service
  type: ClusterIP
