apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  ## namespace: medisupply
  labels:
    app: warehouse-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouse-service
      version: v1
  template:
    metadata:
      labels:
        app: warehouse-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: warehouse-service
        image: jssierrac1/arqnewgen-medisupply-warehouse-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: warehouse-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8100
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8100
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {}
