apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  ## namespace: medisupply
  labels:
    app: warehouse-service
    service: warehouse-service
spec:
  ports:
  - port: 8100
    targetPort: 8100
    name: http
    protocol: TCP
  selector:
    app: warehouse-service
  type: ClusterIP
