apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-service-config
  namespace: medisupply
  labels:
    app: warehouse-service
    version: v1
data:
  APP_ENV: "prod"
  WHAREHOUSE_HTTP_PORT_PORT: "8100"
  DB_PATH: "/app/data/warehouse.db"
