apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: go-service-telemetry
  namespace: go-service-obs
spec:
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        request_id:
          operation: UPSERT
          value: "%{REQUEST_ID}"
  tracing:
  - providers:
    - name: jaeger
  accessLogging:
  - providers:
    - name: otel